version: '3.1'

services:
    php-apache:
        container_name: soccer-apache-docker
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8088:80
        volumes:
            - .:/var/www/html
            - ./default.conf:/etc/apache2/sites-enabled/000-default.conf
        depends_on:
            - database

    database:
        image: mysql
        container_name: soccer-mysql-server
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        ports:
            - "4306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password1
            MYSQL_DATABASE: lsoccer
        volumes:
            - ./storage/docker-db:/var/lib/mysql

